# .github/workflows/push.yml
name: PR-Check

# On every pull request to master
on:
  pull_request:
    branches:
      - master

jobs:
  PR-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: |
          yarn install
      - name: Build Check
        run: |
          yarn build
